/* Generated by bin2c, do not edit manually */
#ifndef __foo_h_included
#define __foo_h_included

/* Contents of file readme.txt */
extern const long int readme_txt_size;
extern const unsigned char readme_txt[1755];

#endif    /* __foo_h_included */
