// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace kserialize
{

public enum AssetType : sbyte
{
  Texture = 0,
  Shader = 1,
  Material = 2,
  Mesh = 3,
  Model = 4,
  Prefab = 5,
};


}
